### ISSUE TITLE
フッターUI作成

### ISSUE THREAD

**Issue by yziori** [a-team-golang-web-api/hotel-compare#6]

**Comment by rei-k** [comment]
`import React from 'react';

const Footer = () => {
  return (
    <footer className="bg-base-100 py-10 border-t">
      <div className="container mx-auto px-4">
        <div className="flex justify-between">
          <div className="flex flex-col">
            <img src="/logo.png" alt="Logo" className="mb-4 h-10 w-auto"/>
            <div className="flex space-x-4">
              <a href="#" aria-label="X">
                <i className="fab fa-x text-xl"></i>
              </a>
              <a href="#" aria-label="Instagram">
                <i className="fab fa-instagram text-xl"></i>
              </a>
              <a href="#" aria-label="YouTube">
                <i className="fab fa-youtube text-xl"></i>
              </a>
              <a href="#" aria-label="LinkedIn">
                <i className="fab fa-linkedin text-xl"></i>
              </a>
            </div>
          </div>
          <div className="flex space-x-20">
            <div>
              <h4 className="font-bold mb-2">Use cases</h4>
              <ul>
                <li><a href="#" className="text-base-content">UI design</a></li>
                <li><a href="#" className="text-base-content">UX design</a></li>
                <li><a href="#" className="text-base-content">Wireframing</a></li>
                <li><a href="#" className="text-base-content">Diagramming</a></li>
                <li><a href="#" className="text-base-content">Brainstorming</a></li>
                <li><a href="#" className="text-base-content">Online whiteboard</a></li>
                <li><a href="#" className="text-base-content">Team collaboration</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold mb-2">Explore</h4>
              <ul>
                <li><a href="#" className="text-base-content">Design</a></li>
                <li><a href="#" className="text-base-content">Prototyping</a></li>
                <li><a href="#" className="text-base-content">Development features</a></li>
                <li><a href="#" className="text-base-content">Design systems</a></li>
                <li><a href="#" className="text-base-content">Collaboration features</a></li>
                <li><a href="#" className="text-base-content">Design process</a></li>
                <li><a href="#" className="text-base-content">FigJam</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold mb-2">Resources</h4>
              <ul>
                <li><a href="#" className="text-base-content">Blog</a></li>
                <li><a href="#" className="text-base-content">Best practices</a></li>
                <li><a href="#" className="text-base-content">Colors</a></li>
                <li><a href="#" className="text-base-content">Color wheel</a></li>
                <li><a href="#" className="text-base-content">Support</a></li>
                <li><a href="#" className="text-base-content">Developers</a></li>
                <li><a href="#" className="text-base-content">Resource library</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
import React from 'react';

const Footer = () => {
  return (
    <footer className="bg-base-100 py-10 border-t">
      <div className="container mx-auto px-4">
        <div className="flex justify-between">
          <div className="flex flex-col">
            <img src="/logo.png" alt="Logo" className="mb-4 h-10 w-auto"/>
            <div className="flex space-x-4">
              <a href="#" aria-label="X">
                <i className="fab fa-x text-xl"></i>
              </a>
              <a href="#" aria-label="Instagram">
                <i className="fab fa-instagram text-xl"></i>
              </a>
              <a href="#" aria-label="YouTube">
                <i className="fab fa-youtube text-xl"></i>
              </a>
              <a href="#" aria-label="LinkedIn">
                <i className="fab fa-linkedin text-xl"></i>
              </a>
            </div>
          </div>
          <div className="flex space-x-20">
            <div>
              <h4 className="font-bold mb-2">Use cases</h4>
              <ul>
                <li><a href="#" className="text-base-content">UI design</a></li>
                <li><a href="#" className="text-base-content">UX design</a></li>
                <li><a href="#" className="text-base-content">Wireframing</a></li>
                <li><a href="#" className="text-base-content">Diagramming</a></li>
                <li><a href="#" className="text-base-content">Brainstorming</a></li>
                <li><a href="#" className="text-base-content">Online whiteboard</a></li>
                <li><a href="#" className="text-base-content">Team collaboration</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold mb-2">Explore</h4>
              <ul>
                <li><a href="#" className="text-base-content">Design</a></li>
                <li><a href="#" className="text-base-content">Prototyping</a></li>
                <li><a href="#" className="text-base-content">Development features</a></li>
                <li><a href="#" className="text-base-content">Design systems</a></li>
                <li><a href="#" className="text-base-content">Collaboration features</a></li>
                <li><a href="#" className="text-base-content">Design process</a></li>
                <li><a href="#" className="text-base-content">FigJam</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold mb-2">Resources</h4>
              <ul>
                <li><a href="#" className="text-base-content">Blog</a></li>
                <li><a href="#" className="text-base-content">Best practices</a></li>
                <li><a href="#" className="text-base-content">Colors</a></li>
                <li><a href="#" className="text-base-content">Color wheel</a></li>
                <li><a href="#" className="text-base-content">Support</a></li>
                <li><a href="#" className="text-base-content">Developers</a></li>
                <li><a href="#" className="text-base-content">Resource library</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
`

**Comment by rei-k** [comment]
特になし
